site_name: Timtek Utilities
repo_url: https://github.com/Tigra-Astronomy/TA.Utilities
# Render from the Obsidian vault directory (note the space in the path)
docs_dir: "Documentation/Timtek Utilities"
use_directory_urls: true

theme:
  name: material

plugins:
  - search
  - mike
  - roamlinks

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - Overview: Overview.md
  - Versioning: Versioning.md
  - Diagnostics and Logging: Diagnostics and Logging.md
  - Core:
    - SemanticVersion: Core/SemanticVersion.md
    - Maybe: Core/Maybe.md
    - Octet: Core/Octet.md
    - Code Contracts: Core/Code Contracts.md
    - Display Equivalent: Core/Display Equivalent.md
    - ASCII Mnemonic Expansion: Core/ASCII Mnemonic Expansion.md
    - Async Helpers: Core/Async Helpers.md
    - Property Binding: Core/Property Binding.md
    - Finite State Machine: Core/Finite State Machine.md
  - Areas for Improvement:
    - FSM SOLID Analysis: Areas for Improvement/FSM SOLID Analysis.md
