site_name: Timtek Utilities
repo_url: https://github.com/Tigra-Astronomy/TA.Utilities
# Render from the Obsidian vault directory (note the space in the path)
docs_dir: "Documentation/Timtek Utilities"
use_directory_urls: true

theme:
  name: material

plugins:
  - search
  - mike

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code

extra:
  version:
    provider: mike

nav:
  - Home: index.md
